# Task 3

In [1]:
import numpy as np
import pandas as pd

#from sklearn.linear_model import Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import cross_val_score
from sklearn.metrics import make_scorer, f1_score
from sklearn.preprocessing import OneHotEncoder

In [2]:
test_data = pd.read_csv('test.csv') #These are just features names (48000)
train_data = pd.read_csv('train.csv') #Says if something is active or not (112000)

num_train_data = len(train_data)

In [3]:
train_feature = np.array(train_data['Sequence'])
train_output = np.array(train_data['Active'])
train_feature_splitted = []

In [4]:
for i, feature in enumerate(train_feature):
    train_feature_splitted.append([])
    for s in list(feature):
        train_feature_splitted[i].append(ord(s))
        
train_feature_splitted = np.array(train_feature_splitted)

In [5]:
score_func = make_scorer(f1_score)

In [6]:
%%time
model = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(model, train_feature_splitted, train_output, cv=5, scoring=score_func)

print(scores)

[0.29186155 0.27677725 0.30698529 0.30882353 0.32618826]
CPU times: user 4.79 s, sys: 26.1 ms, total: 4.81 s
Wall time: 4.81 s


In [7]:
%%time
model = DecisionTreeClassifier(criterion='entropy')
scores = cross_val_score(model, train_feature_splitted, train_output, cv=5, scoring=score_func)

print(scores)

[0.75285628 0.74685817 0.75660161 0.75656325 0.74069699]
CPU times: user 557 ms, sys: 23.9 ms, total: 581 ms
Wall time: 580 ms


In [8]:
%%time
model = RandomForestClassifier(criterion='entropy')
scores = cross_val_score(model, train_feature_splitted, train_output, cv=5, scoring=score_func)

print(scores)

[0.74544312 0.71761658 0.73716759 0.73718365 0.73363001]
CPU times: user 23.8 s, sys: 103 ms, total: 23.9 s
Wall time: 23.9 s
